phenopackets/phenopacket-tools

phenotools-validator-jsonschema/src/main/java/org/phenopackets/phenotools/validator/jsonschema/ClasspathJsonSchemaValidatorFactory.java, phenotools-validator-jsonschema/src/main/resources/schema/phenopacket-schema-2-0.json
Fix issue #27 - Change object to array type for disease::diseaseStage and disease::clinicalTnmFinding
=> Rename phenopacket-general-schema.json to phenopacket-schema-2-0.json

phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/constants/SpatialPattern.java
Generated from HPO hierarchy with script.
=> adding constants for SpatialPattern

phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/InterpretationBuilder.java, phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/MetaDataBuilder.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/PhenopacketTools.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/command/HtmlOutputCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/examples/NemalineMyopathyPrenatal.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/examples/Retinoblastoma.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/html/HtmlOutputter.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/html/HtmlUtil.java, phenopacket-tools-converter/src/test/java/org/phenopackets/phenopackettools/converter/PhenopacketConverterTest.java
New command to output a simple HTML file with the contents of a phenopacket to support human consumption. Still needs more features but the basics are working
=> Html phenopacket output

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/command/ExamplesCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/examples/GlaucomaSurgery.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/examples/PhenopacketExamples.java
I created a framework for the glaucoma example
=> glaucoma example framework

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/command/ExamplesCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/examples/Pseudoexfoliation.java
=> Pseudoexfoliation

phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/IndividualBuilder.java, phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/PhenotypicFeatureBuilder.java, phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/TherapeuticRegimenBuilder.java
This PR extends builders with a couple of methods that I think were forgotten/omitted. The changes comprise of just several lines, please see the commit messages and changes for more info.
=> Extend builders with missing methods.

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/examples/BethlehamMyopathy.java
added VCF data to an example. I looked through the examples and they seem good now.
=> revising our examples

phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/Resources.java
@ielis @julesjacobsen as discussed by email
=> Adding HGNC Resource builder

phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/GeneDescriptorBuilder.java
Fixes https://github.com/phenopackets/phenopacket-tools/issues/60
=> correcting name of var and adding documentation for GeneDescriptor

phenopacket-tools-validator-jsonschema/src/main/resources/org/phenopackets/phenopackettools/validator/jsonschema/vrs.json, phenopacket-tools-validator-jsonschema/src/main/resources/org/phenopackets/phenopackettools/validator/jsonschema/vrsatile.json, phenopacket-tools-validator-jsonschema/src/test/resources/org/phenopackets/phenopackettools/validator/jsonschema/bethlem-myopathy.json, phenopacket-tools-validator-jsonschema/src/test/resources/org/phenopackets/phenopackettools/validator/jsonschema/example-cohort.json, phenopacket-tools-validator-jsonschema/src/test/resources/org/phenopackets/phenopackettools/validator/jsonschema/example-family.json
Ensure correctness of the validation parts that use VRS and VERSATILE JSON schemas.
=> Update VRS and VERSATILE validation

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/command/ConvertCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/command/ExamplesCommand.java, phenopacket-tools-io/pom.xml, phenopacket-tools-io/src/main/java/module-info.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/JsonPrinter.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/NaiveYamlPrinter.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/PhenopacketPrinter.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/PhenopacketPrinterFactory.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/PhenopacketPrinterFactoryException.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/PhenopacketPrinterFactoryImpl.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/base/BasePhenopacketParser.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/base/NaiveYamlParser.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/v1/V1PhenopacketParser.java, phenopacket-tools-io/src/main/java/org/phenopackets/phenopackettools/io/v2/V2PhenopacketParser.java, phenopacket-tools-io/src/test/java/org/phenopackets/phenopackettools/io/NaiveYamlPrinterTest.java, phenopacket-tools-io/src/test/java/org/phenopackets/phenopackettools/io/v1/V1PhenopacketParserTest.java, phenopacket-tools-io/src/test/java/org/phenopackets/phenopackettools/io/v2/V2PhenopacketParserTest.java, phenopacket-tools-io/src/test/resources/org/phenopackets/phenopackettools/io/v1/cohort.yaml, phenopacket-tools-io/src/test/resources/org/phenopackets/phenopackettools/io/v1/family.yaml, phenopacket-tools-io/src/test/resources/org/phenopackets/phenopackettools/io/v1/phenopacket.yaml, phenopacket-tools-io/src/test/resources/org/phenopackets/phenopackettools/io/v2/cohort.yaml, phenopacket-tools-io/src/test/resources/org/phenopackets/phenopackettools/io/v2/family.yaml, phenopacket-tools-io/src/test/resources/org/phenopackets/phenopackettools/io/v2/phenopacket.yaml
=> Implement YAML I/O

constants/Unit.tsv, constants/create_rtd.py, docs/constants.rst, phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/constants/Unit.java
Reverts phenopackets/phenopacket-tools#130
We should not have merged into `main` but to `develop`.
=> Revert "change miligram per day to milligram per liter"

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/command/ValidateCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/command/validate/ValidateCohortCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/command/validate/ValidateFamilyCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/command/validate/ValidatePhenopacketCommand.java, phenopacket-tools-validator-core/src/main/java/org/phenopackets/phenopackettools/validator/core/ValidationWorkflowRunnerBuilder.java, phenopacket-tools-validator-core/src/main/java/org/phenopackets/phenopackettools/validator/core/package-info.java, phenopacket-tools-validator-jsonschema/src/main/java/org/phenopackets/phenopackettools/validator/jsonschema/BaseValidationWorkflowRunnerBuilder.java, phenopacket-tools-validator-jsonschema/src/main/java/org/phenopackets/phenopackettools/validator/jsonschema/JsonSchemaValidationWorkflowRunner.java, phenopacket-tools-validator-jsonschema/src/main/java/org/phenopackets/phenopackettools/validator/jsonschema/JsonSchemaValidationWorkflowRunnerBuilder.java
Remove the concept of syntax and semantic validators as it turned out not to be too useful.
=> Remove the concept of syntax and semantic validators.

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/examples/Marfan.java
=> Removing space from CURIE

.github/workflows/pages.yml
=> Work on documentation

constants/AllelicState.tsv, docs/constants.rst, phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/VariationDescriptorBuilder.java, phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/constants/AllelicState.java
Add [unspecified zygosity](http://purl.obolibrary.org/obo/GENO_0000137) into `AllelicState` constants.
=> Add unspecified zygosity into AllelicState constants.

phenopacket-tools-builder/src/main/java/org/phenopackets/phenopackettools/builder/builders/TimeElements.java
Add several static constructors to handle special situations.
=> Increase granularity of static constructors for `TimeElement`s.

phenopacket-tools-cli/src/main/java/module-info.java, pom.xml
Update dependency versions to unlock latest features and mitigate security vulnerabilities.
=> Update dependency versions.

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/examples/Pseudoexfoliation.java
Fix the pseudoexfoliation example. Correct SNOMEDCT code and add a resource.
=> Fix SNOMEDCT issues in pseudoexfoliation phenopacket.

phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/command/ExamplesCommand.java, phenopacket-tools-cli/src/main/java/org/phenopackets/phenopackettools/cli/examples/ExampleCohort.java
Add an example for a `Cohort` message. The cohort consists of two members.
=> Add an example cohort.

.github/workflows/pages.yml
Allow generating examples by snapshots, silence Maven.
=> Allow generating examples by snapshots, silence Maven.

.github/workflows/pages.yml
Update links to documentation in README.md on the `develop` branch.
=> Update links to documentation in README (`develop`)
